#在配置文件中注明自己的服务注册中心的地址，application.yml配置文件如下
server:
  port: 8762

spring:
  application:
    name: service-client #这个name很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  mvc:
      view:
        prefix: /templates/
        suffix: .ftl

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.168:8761/eureka/
  instance: #处理eureka的自我保护机制
    statusPageUrlPath: /swagger-ui.html
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}